# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pipeline_pb2 as agent__pipeline__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubAgentServiceStub:
    """Service implemented by all sub-agents (both TypeScript and Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteStep = channel.unary_stream(
                '/vda.agent.v1.SubAgentService/ExecuteStep',
                request_serializer=agent__pipeline__pb2.StepExecutionRequest.SerializeToString,
                response_deserializer=agent__pipeline__pb2.StepStreamEvent.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/vda.agent.v1.SubAgentService/CheckHealth',
                request_serializer=agent__pipeline__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent__pipeline__pb2.HealthResponse.FromString,
                _registered_method=True)


class SubAgentServiceServicer:
    """Service implemented by all sub-agents (both TypeScript and Python)
    """

    def ExecuteStep(self, request, context):
        """Executes a designated DAG step and streams real-time reasoning logs and artifacts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Health and readiness check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteStep': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStep,
                    request_deserializer=agent__pipeline__pb2.StepExecutionRequest.FromString,
                    response_serializer=agent__pipeline__pb2.StepStreamEvent.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=agent__pipeline__pb2.HealthRequest.FromString,
                    response_serializer=agent__pipeline__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vda.agent.v1.SubAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vda.agent.v1.SubAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubAgentService:
    """Service implemented by all sub-agents (both TypeScript and Python)
    """

    @staticmethod
    def ExecuteStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vda.agent.v1.SubAgentService/ExecuteStep',
            agent__pipeline__pb2.StepExecutionRequest.SerializeToString,
            agent__pipeline__pb2.StepStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vda.agent.v1.SubAgentService/CheckHealth',
            agent__pipeline__pb2.HealthRequest.SerializeToString,
            agent__pipeline__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
