# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_pipeline.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent_pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61gent_pipeline.proto\x12\x0cvda.agent.v1\"\xca\x01\n\x14StepExecutionRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x13\n\x0buser_prompt\x18\x04 \x01(\t\x12\x12\n\nagent_role\x18\x05 \x01(\t\x12\x34\n\x0finput_artifacts\x18\x06 \x03(\x0b\x32\x1b.vda.agent.v1.InputArtifact\x12\x1e\n\x16\x65xecution_context_json\x18\x07 \x01(\t\"Q\n\rInputArtifact\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x15\n\rartifact_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_json\x18\x03 \x01(\t\"\xb3\x01\n\x0fStepStreamEvent\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.vda.agent.v1.StepStreamEvent.EventType\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x14output_artifact_json\x18\x03 \x01(\t\":\n\tEventType\x12\t\n\x05TRACE\x10\x00\x12\t\n\x05TOKEN\x10\x01\x12\x0c\n\x08\x43OMPLETE\x10\x02\x12\t\n\x05\x45RROR\x10\x03\"\x0f\n\rHealthRequest\"<\n\x0eHealthResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2\xaf\x01\n\x0fSubAgentService\x12R\n\x0b\x45xecuteStep\x12\".vda.agent.v1.StepExecutionRequest\x1a\x1d.vda.agent.v1.StepStreamEvent0\x01\x12H\n\x0b\x43heckHealth\x12\x1b.vda.agent.v1.HealthRequest\x1a\x1c.vda.agent.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPEXECUTIONREQUEST']._serialized_start=39
  _globals['_STEPEXECUTIONREQUEST']._serialized_end=241
  _globals['_INPUTARTIFACT']._serialized_start=243
  _globals['_INPUTARTIFACT']._serialized_end=324
  _globals['_STEPSTREAMEVENT']._serialized_start=327
  _globals['_STEPSTREAMEVENT']._serialized_end=506
  _globals['_STEPSTREAMEVENT_EVENTTYPE']._serialized_start=448
  _globals['_STEPSTREAMEVENT_EVENTTYPE']._serialized_end=506
  _globals['_HEALTHREQUEST']._serialized_start=508
  _globals['_HEALTHREQUEST']._serialized_end=523
  _globals['_HEALTHRESPONSE']._serialized_start=525
  _globals['_HEALTHRESPONSE']._serialized_end=585
  _globals['_SUBAGENTSERVICE']._serialized_start=588
  _globals['_SUBAGENTSERVICE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
